server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
      - id: company
        uri: http://localhost:8081/
        predicates:
        - Path=/company/**
      - id: broker
        uri: http://localhost:8082/
        predicates:
        - Path=/broker/**
      - id: client
        uri: http://localhost:8083/
        predicates:
        - Path=/client/**
      - id: property
        uri: http://localhost:8084/
        predicates:
        - Path=/property/**
      - id: mail
        uri: http://localhost:8085/
        predicates:
        - Path=/mail/**  
      - id: authentication
        uri: http://localhost:8087/
        predicates:
        - Path=/authentication/**             
        
#G2IT_Realstate_Config_Service = 8086
#G2IT_Realstate_Authentication_Service = 8087      
