spring:
  model:
    package: com.g2it.realstate.company.model
  datasource:
    jdbcUrl: jdbc:mysql://main-db/property_mangement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 0
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ecommConnectionPool
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8081
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka
